logging:
  level:
    root: error
    com.cn: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_test?serverTimezone=GMT%2B8
    username: root
    password: root
